In [ ]:
**Questions**

In [66]:
# Columns: [Age, Math Marks, Science Marks]

data = n.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

#Get the shape of the matrix.

#Find the average age of students. 

#Extract Math marks of all students.
    
#Find the highest Science mark.

#Get details of the student who scored more than 90 in Math.
    
#Increase Math marks of all students by 5.
    
#Find how many students are younger than 19.

#Calculate the average marks in each subject (column-wise mean).

#Get data of students who scored at least 80 in both subjects.

#Replace all Science marks < 75 with 0.

In [68]:
**Analysis**

In [172]:
import numpy as n

In [173]:
# Columns: [Age, Math Marks, Science Marks]
data = n.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

shape= data.shape
print("the shape is",shape)

the shape is (5, 3)


In [174]:
average_age=n.mean(data[:,0])
print("average age is",average_age)

average age is 18.4


In [175]:
maths_marks=data[:,1]
print("all maths marks:",maths_marks)

all maths marks: [85 92 76 65 90]


In [176]:
highest_science_marks=n.max(data[:,2])
print("highest marks achieved in science is:",highest_science_marks)

highest marks achieved in science is: 95


In [177]:
student_info=data[:,1]>90
detail=data[student_info]
print("detail of a student who scored more than 90:",detail)

detail of a student who scored more than 90: [[19 92 88]]


In [178]:
data2=data.copy()
data2[:,1]+=5
print("the new updated data is:\n",data2)

the new updated data is:
 [[18 90 78]
 [19 97 88]
 [17 81 95]
 [18 70 70]
 [20 95 85]]


In [179]:
age=data[:,0]<19
count=n.sum(age)
print(f"there are total {count} students who are below 19")

there are total 3 students who are below 19


In [180]:
average_marks_subjects=n.mean(data[:,1:3],axis=0)
print("the average marks in each subject:")
average_marks_subjects

the average marks in each subject:


array([81.6, 83.2])

In [181]:
score=data[:,1:3]>=80
score_detail=data[score.all(axis=1)]
print("the detail of the students are here:",score_detail)

the detail of the students are here: [[19 92 88]
 [20 90 85]]


In [182]:
new_data=data.copy()
marks=new_data[:,2]<75
new_data[marks,2]=0
print("the new data now:\n",new_data)

the new data now:
 [[18 85 78]
 [19 92 88]
 [17 76 95]
 [18 65  0]
 [20 90 85]]
